name: kodicmd testing

on:
  push:
    branches: [ kodicmd ]
  pull_request:
    branches: [ kodicmd ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install git+https://github.com/jonisb/jsbc.compat.git#egg=jsbc.compat
        pip install git+https://github.com/jonisb/Toolbox.git#egg=jsbc.Toolbox
        pip install git+https://github.com/jonisb/jsbc.network.git#egg=jsbc.network
        pip install pytest
        
    - name: Install jsbc.KodiLib
      run: |
        pip install .        
    
    - name: Install Kodi
      run: |
        sudo apt-get update
        sudo apt-get install -y kodi
    
    - name: Run Kodi
      run: |
        xvfb-run -a kodi &
        KODI_PID=$!
        sleep 60 # Give kodi time to start

    - name: Run tests
      run: pytest tests/

    - name: Stop Kodi
      run: |
        if [ -n "$KODI_PID" ]; then
          kill $KODI_PID || true
        fi
    - name: Upload log files
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        path: |
          ~/.kodi/kodi.log
